name: .NET CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: SubverseIM.App
    runs-on: self-hosted

    container: 
      image: mcr.microsoft.com/dotnet/sdk:8.0
      
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - name: Add Avalonia Nuget feed
      run: dotnet nuget add source https://nuget-feed-all.avaloniaui.net/v3/index.json
    - name: Restore dependencies
      run: dotnet restore SubverseIM.App/SubverseIM.Headless/SubverseIM.Headless.csproj
    - name: Build SubverseIM
      run: dotnet build SubverseIM.App/SubverseIM.Headless/SubverseIM.Headless.csproj --no-restore
    - name: Test SubverseIM
      run: dotnet test SubverseIM.App/SubverseIM.Headless/SubverseIM.Headless.csproj --no-build --verbosity normal
  publish:
    name: SubverseIM.Android
    runs-on: self-hosted
    
    container: 
      image: mobiledevops/android-sdk-image
      
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Add Avalonia Nuget feed
        run: dotnet nuget add source https://nuget-feed-all.avaloniaui.net/v3/index.json
      - name: Test SubverseIM
        run: dotnet test SubverseIM.App/SubverseIM.Headless/SubverseIM.Headless.csproj
      - name: Restore workloads
        run: dotnet workload restore SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj
      - name: Restore dependencies
        run: dotnet restore SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj
      - name: Restore Android signing keys
        run: (echo ${{ secrets.KEYSTORE }} | base64 --decode) > SubverseIM.App/SubverseIM.Android/ChosenFewKey.keystore
      - name: Build & publish SubverseIM.Android
        run: dotnet publish SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj --configuration Release --output /home/tc/publish/android -m:1 -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=ChosenFewKey.keystore -p:AndroidSigningKeyAlias=ChosenFewKey -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} -p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }}
      - name: Upload .apk as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "com.ChosenFewSoftware.SubverseIM-Signed.apk"
          path: "/home/tc/publish/android/com.ChosenFewSoftware.SubverseIM-Signed.apk"