name: .NET CI Publish

on: 
  push:
    tags:
    - '*'

jobs:
  publish:
    name: SubverseIM.Android
    runs-on: self-hosted
    permissions:
      contents: write

    container: 
      image: mobiledevops/android-sdk-image
      
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Add Avalonia Nuget feed
      run: dotnet nuget add source https://nuget-feed-all.avaloniaui.net/v3/index.json
    - name: Test SubverseIM
      run: dotnet test SubverseIM.App/SubverseIM.Headless/SubverseIM.Headless.csproj
    - name: Restore workloads
      run: dotnet workload restore SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj
    - name: Restore dependencies
      run: dotnet restore SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj
    - name: Restore Android signing keys
      run: (echo ${{ secrets.KEYSTORE }} | base64 --decode) > SubverseIM.App/SubverseIM.Android/ChosenFewKey.keystore
    - name: Build & publish SubverseIM.Android
      run: dotnet publish SubverseIM.App/SubverseIM.Android/SubverseIM.Android.csproj --configuration Release --output /home/tc/publish/android -m:1 -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=ChosenFewKey.keystore -p:AndroidSigningKeyAlias=ChosenFewKey -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} -p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }}
    - name: Create new release
      id: gh_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/tc/publish/android/com.ChosenFewSoftware.SubverseIM-Signed.apk"
        generateReleaseNotes: true
    - name: Create release notes for Google Play
      run: "mkdir /home/tc/publish/android/whatsnew && (echo Full release notes are available at the link listed below: && echo ${{ steps.gh_release.outputs.html_url }}) > /home/tc/publish/android/whatsnew/whatsnew-en-US"
    - name: Publish to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.ChosenFewSoftware.SubverseIM
        releaseFiles: "/home/tc/publish/android/com.ChosenFewSoftware.SubverseIM-Signed.aab"
        whatsNewDirectory: "/home/tc/publish/android/whatsnew"
        track: internal
